= Hardware & Edge Computing (ESP32-C3)

The edge layer of QuakeGuard is designed to operate on resource-constrained microcontrollers, specifically targeting the ESP32-C3 SuperMini platform (RISC-V architecture)[cite: 1]. The node interfaces with an ADXL345 digital accelerometer to acquire, filter, and analyze seismic data locally, transmitting only cryptographically signed anomaly reports to conserve bandwidth[cite: 1].

== Hardware Configuration & Interfacing

Due to the specific physical layout of the ESP32-C3 SuperMini, the I2C bus is software-mapped to non-standard GPIO pins[cite: 1]:
- *SDA (Data):* Mapped to GPIO 7, requiring internal pull-up resistors[cite: 1].
- *SCL (Clock):* Mapped to GPIO 8, requiring internal pull-up resistors[cite: 1].
- *Power Constraints:* The ADXL345 is powered strictly via the 3.3V rail; applying 5V will result in immediate hardware damage[cite: 1].

The sensor operates at a 100Hz sampling rate (`ADXL345_DATARATE_100_HZ`) with a measurement range of $\pm$16G (`ADXL345_RANGE_16_G`)[cite: 1]. To prevent I2C bus race conditions during startup, the sensor object is instantiated dynamically in memory only after the hardware bus is fully stabilized[cite: 1].

== Digital Signal Processing (DSP) Pipeline

Raw acceleration data undergoes multiple stages of local processing before being evaluated:
- *High-Pass Filter (HPF):* A digital filter (`HPF_ALPHA = 0.9f`) isolates the dynamic vibration data by subtracting the static DC component (Earth's gravity, approx. 9.81 $m/s^2$)[cite: 1].
- *Noise Gate:* Micro-vibrations below the empirical threshold of 0.04G are clamped to zero to prevent false positives generated by electrical noise[cite: 1].
- *Dropout Protection:* The firmware automatically drops frames reporting near-zero absolute acceleration (less than 2.0 $m/s^2$ prior to filtering), effectively mitigating corrupted readings caused by temporary I2C wire disconnects[cite: 1].

== STA/LTA Seismic Detection Algorithm

QuakeGuard implements the industry-standard Short-Term Average / Long-Term Average (STA/LTA) algorithm[cite: 1]. The implementation utilizes a custom, memory-efficient `RingBuffer` template class in C++ to maintain rolling sums, allowing $O(1)$ average calculations[cite: 1].
- *Short-Term Window (STA):* 100 samples (1 second of telemetry), representing the immediate seismic transient[cite: 1].
- *Long-Term Window (LTA):* 1000 samples (10 seconds of telemetry), representing the background noise floor[cite: 1].
- *Trigger Condition:* An earthquake is registered when the STA/LTA ratio exceeds `1.8f`, provided the STA absolute value is also above the noise floor[cite: 1].

== FreeRTOS Task Architecture

The firmware utilizes FreeRTOS to decouple time-critical sensor acquisition from network latency[cite: 1].
- *`sensorTask`:* Pinned to a high priority, it wakes exactly every 10ms to poll the ADXL345 and execute the DSP pipeline[cite: 1]. Upon detecting a seismic event, it pushes a `SeismicEvent` struct to the `eventQueue`[cite: 1].
- *`networkTask`:* Operates asynchronously at a lower priority[cite: 1]. It consumes the `eventQueue`, synchronizes the event timestamp via NTP (`pool.ntp.org`), signs the payload, and dispatches the MQTT message[cite: 1]. This design ensures that network blocking or Wi-Fi reconnects never halt the continuous monitoring of the accelerometer[cite: 1].
- *`gnssTask` (optional):* When the GNSS subsystem is compiled in, a dedicated task (priority 2) continuously feeds NMEA frames into the parser so the coordinate pipeline is always live[cite: 1].

== Optional GNSS Subsystem (v1.3 Readiness)

Since v1.2.1 the firmware is *GNSS-ready*: an optional module parses NMEA data from a u-blox / NEO-6M / NEO-M8N receiver over the secondary UART (RX GPIO 0, TX GPIO 1, 9600 baud)[cite: 1]. The module is compiled #strong[only] when `GNSS_ENABLED=1` is present in `esp32_config.env`, so the default build stays hermetic and pulls no `TinyGPSPlus` dependency[cite: 1].

- *Last-Known Fix Persistence:* Every reliable fix is saved into NVS (namespace `quake-gnss`, at most once per 60 seconds to limit flash wear)[cite: 1]. Provisioning therefore reports real coordinates even before the first fix after a cold boot[cite: 1].
- *Staleness Handling:* A live fix older than 10 seconds is treated as stale and the firmware falls back to the last-known value[cite: 1].
- *Provisioning Integration:* During `/devices/register`, the node reports the live GNSS fix when available, else the last-known-from-NVS fix; when no fix exists at all, coordinates are omitted so the backend can assign the zone once placed[cite: 1].
- *Scope Boundary:* NTP + PPS timestamp discipline is explicitly deferred to v1.3 (see ROADMAP) — this module only guarantees the coordinates pipeline is ready for the GNSS upgrade[cite: 1].