name: PR Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title-validation:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Semantic PR Check
        uses: amannn/action-semantic-pull-request@e32d7e603df1aa1ba07e981f2a23455dee596825
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            backend
            frontend
            iot
            ci
            deps
            deps-dev
            core
            style
            fullstack
          requireScope: true